name: Test & Deploy to Production

on:
  push:
    branches:
      - master

jobs:

  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: test_database
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
          MYSQL_ROOT_PASSWORD: root_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --host=mysql --user=root --password=root_password"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:

      - name: Set up PHP with Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app php:8.0-cli bash -c "
          apt-get update && apt-get install -y unzip && \
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer"

      - uses: actions/checkout@v4

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Set up MySQL Database Connection
        run: |
          sed -i '/^DB_CONNECTION=/d' .env
          sed -i '/^DB_HOST=/d' .env
          sed -i '/^DB_PORT=/d' .env
          sed -i '/^DB_DATABASE=/d' .env
          sed -i '/^DB_USERNAME=/d' .env
          sed -i '/^DB_PASSWORD=/d' .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=mysql" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=test_database" >> .env
          echo "DB_USERNAME=test_user" >> .env
          echo "DB_PASSWORD=test_password" >> .env

      - name: Wait for MySQL to be ready
        run: |
          until mysql -h mysql -u test_user -ptest_password -e "select 1"; do
            echo "Waiting for MySQL to be ready..."
            sleep 2
          done

      - name: Migrate Database
        env:
          DB_CONNECTION: mysql
          DB_HOST: mysql
          DB_PORT: 3306
          DB_DATABASE: test_database
          DB_USERNAME: test_user
          DB_PASSWORD: test_password
        run: php artisan migrate --force

      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: mysql
          DB_HOST: mysql
          DB_PORT: 3306
          DB_DATABASE: test_database
          DB_USERNAME: test_user
          DB_PASSWORD: test_password
        run: php artisan test

  deploy:
    runs-on: ubuntu-latest
    needs: laravel-tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Decode and Set Up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" | base64 --decode > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -p 65002 -H ${{ secrets.SERVER }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: ssh -i ~/.ssh/deploy_key -p 65002 ${{ secrets.SSH_USER }}@${{ secrets.SERVER }} "${{ secrets.DEPLOYMENT_COMMAND }}"
